### ISSUE TITLE
The Payment model is not really storing records of payments

### ISSUE THREAD

**Issue by jerryjohnjacob** [shshamim63/Payment_calculator#2]
A payments table would be expected to store records of actual payments. The corresponding model would have business logic relevant to the individual payments. However, the modelling in this application does not reflect that. What would be a good way to fix this?

**Comment by shshamim63** [comment]
From your comment, I think you meant to store all the calculated payment instances under a user's request. Isn't it? If that is the case then instead of new I can call the create method to store each instance after the calculation.
___
If I did not get it properly can you please elaborate on the issue?

**Comment by jerryjohnjacob** [comment]
Think of it this way. If this were a production application, would you make any changes to the modelling?

**Comment by shshamim63** [comment]
Yes, Now I got it. A loan model that will be responsible for storing users' loan info and under that there will be projected payments.

**Comment by jerryjohnjacob** [comment]
I see the PR. Before I take a deeper look, can you write tests for the code you have now?

**Comment by shshamim63** [comment]
I have added tests for the models. You can check the PR.
